name: eborrow
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  camera: ^0.11.2
  mobile_scanner: ^7.0.1
  permission_handler: ^11.0.1
  supabase_flutter: ^2.10.2
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.5+1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
  uuid: ^4.5.1
  flutter_native_splash: ^2.4.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/nud.png
    - assets/e-borrow logo.png
    - assets/e-borrow logo new.png
    - assets/google logo.png
    - assets/app-icon.png

# native splash screen configuration
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/e-borrow logo new.png

  android: true
  ios: true
  web: true

  color_dark: "#2B326B"
  image_dark: assets/e-borrow logo new.png

  android_12:
    image: assets/e-borrow logo new.png
    icon_background_color: "#FFFFFF"
    color: "#FFFFFF"

  fullscreen: true

# app icon config
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-icon.png"
  min_sdk_android: 21

  # Adaptive icon for Android (replaces the android: true above for adaptive icons)
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app-icon.png"

  # Remove default Flutter icon transparency
  remove_alpha_ios: true

  # Web icon
  web:
    generate: true
    image_path: "assets/app-icon.png"
    background_color: "#2B326B"
    theme_color: "#2B326B"